language: node_js

node_js:
  - "node"
  - "7"

branches:
  only:
  - master

cache: npm

install:
  - npm i

script:
  - echo "skipping test"

jobs:
  include:
    - stage: docs release
      node_js: "node"
      script:
        - bash scripts/deploy-docs.sh
      deploy:
        local-dir: gh-pages
        provider: pages
        skip-cleanup: true
        github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
        keep-history: true
        on:
          branch: master