language: node_js

node_js:
  - "node"

branches:
  only:
  - master
  - /^v.*$/

cache: npm

install:
  - npm i

script:
  - echo "Skipped this stage."

stages:
  - test
  - release

jobs:
  include:
    - stage: test
      script:
        - npm test
        - npm run codecov
    - stage: release
      if: branch = master
      script:
        - echo "Begin to release docs..."
        - npm run build
        - bash scripts/deploy-docs.sh
      deploy:
        local-dir: gh-pages
        provider: pages
        skip-cleanup: true
        github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
        keep-history: true
        on:
          branch: master
    - stage: release
      script:
        - echo "Begin releasing to NPM..."
        - npm run build
      if: tag =~ ^v
      deploy:
        provider: npm
        email: $NPM_EMAIL_ADDRESS
        api_key: $NPM_TOKEN
        on:
          tags: true