language: node_js

node_js:
  - "node"

branches:
  only:
  - master
  - /^v.*$/

cache: npm

install:
  - npm i

script:
  - echo "Running test suites..."
  - npm test

jobs:
  include:
    - stage: docs release
      node_js: "node"
      script:
        - npm run build
        - bash scripts/deploy-docs.sh
      deploy:
        local-dir: gh-pages
        provider: pages
        skip-cleanup: true
        github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
        keep-history: true
        on:
          branch: master
    - stage: npm release
      node_js: "node"
      script:
        - npm run build
      deploy:
        provider: npm
        api_key: $NPM_TOKEN
        on:
          tags: true